### ISSUE TITLE
"Customer Type" label changes color on selection of any value and becomes difficult to see on dark screen

### ISSUE THREAD

**Issue by jainanupam** [real-coddicted/react-tax-dashboard#12]
1. The "Customer Type" label on first screen of add user flow changes color on selecting any value. After this it becomes quite difficult to see it in a dark screen. Same goes with other labels also in next forms. Either we should not change the color or else make it a different color scheme.
2. On moving between forms via next and back after selection was done, the Customer Type label comes back in original color scheme (as if unselected). This seems a bit counter-intuitive.
Attaching images for reference.

<img width="338" alt="Screenshot 2024-05-25 at 12 35 30 AM" src="https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/e29cfbe2-e564-40a7-bec7-e68ea52c5181">
<img width="283" alt="Screenshot 2024-05-25 at 12 35 41 AM" src="https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/08d59d06-de8e-4215-91c3-5d15fca662b8">
<img width="298" alt="Screenshot 2024-05-25 at 12 35 50 AM" src="https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/22ceedec-5794-4299-a224-7e942aec61ce">

**Comment by payamrastogi** [comment]
Fixed! 
![image](https://github.com/real-coddicted/react-tax-dashboard/assets/3728603/6b9df573-44a1-44a0-8327-1b7844b866b6)
