### ISSUE TITLE
Hide ID column from view on the home screen : /customers page

### ISSUE THREAD

**Issue by jainanupam** [real-coddicted/react-tax-dashboard#20]
<img width="531" alt="Screenshot 2024-05-28 at 6 35 02 PM" src="https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/487ac479-3992-44d9-850a-6d432196c5c5">

**Comment by payamrastogi** [comment]
Fixed!
![image](https://github.com/real-coddicted/react-tax-dashboard/assets/3728603/db7a692c-8812-4cd9-aa21-a5eac9c6bf61)

**Comment by payamrastogi** [comment]
Fixed!
![image](https://github.com/real-coddicted/react-tax-dashboard/assets/3728603/15e3c3b1-02a6-4a78-ab58-7c80dd0e5dc6)
