### ISSUE TITLE
UI: Add Customer - Missing field values in request even though filled on the form

### ISSUE THREAD

**Issue by jainanupam** [real-coddicted/react-tax-dashboard#21]
Certain details like Authorised person, and various fields in participants details (2nd participant onwards I guess) are missing in both add (/api/customer/add) and update (/api/customer/update/{id}) API requests to server.

<img width="940" alt="Screenshot 2024-05-28 at 6 52 20 PM" src="https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/c9e025ac-9979-4da8-8d91-19f074b871bc">

**Comment by payamrastogi** [comment]
Fixed!
![image](https://github.com/real-coddicted/react-tax-dashboard/assets/3728603/ae7bb41d-5fb9-4430-944e-54185972c51f)

**Comment by payamrastogi** [comment]
Fixed!
![image](https://github.com/real-coddicted/react-tax-dashboard/assets/3728603/240a1bd5-11e1-45f9-bce6-4127943cda9b)
