### ISSUE TITLE
UI: Different DOB shown (current-date?) for participant than the one returned in server response

### ISSUE THREAD

**Issue by jainanupam** [real-coddicted/react-tax-dashboard#52]
The DOB returned from server: 

`"dateOfBirth": "2024-03-14",`

DOB displayed on screen (current date):

`2024-06-23`

Attaching screenshot for reference.
![Uploading Screenshot 2024-06-23 at 12.57.18 AM.png…]()

**Comment by payamrastogi** [comment]
Fixed!
