### ISSUE TITLE
Aadhar field mapping seems incorrect

### ISSUE THREAD

**Issue by jainanupam** [real-coddicted/react-tax-dashboard#53]
The Aadhar number field name should be "aadhaar".
Currently, it seems, there are two fields being sent out in the update customer API (see screenshot):
`aadhaar
aadharNumber`

with `aadharNumber` containing the value entered on the form. This should be mapped to aadhaar field only.

<img width="1512" alt="Screenshot 2024-06-23 at 11 25 56 PM" src="https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/968881b4-21e6-43b8-a400-656081de8607">
<img width="834" alt="Screenshot 2024-06-23 at 11 26 18 PM" src="https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/b36c9298-8196-4c21-ad76-3192599cd911">

**Comment by payamrastogi** [comment]
Fixed!
