### ISSUE TITLE
UI: Certain personal info fields in Tax tabs are not getting pre-populated

### ISSUE THREAD

**Issue by jainanupam** [real-coddicted/react-tax-dashboard#73]
![WhatsApp Image 2024-07-03 at 22 34 15](https://github.com/real-coddicted/react-tax-dashboard/assets/3946943/039b9462-6464-4656-bb35-3f56ad5ee194)

**Comment by payamrastogi** [comment]
Data returned by the api doesn't have values

![image](https://github.com/real-coddicted/react-tax-dashboard/assets/3728603/67eed8c5-4ab8-4690-aef0-355869711a80)
