### ISSUE TITLE
UI: Tax Tab - Populate Authorized Person

### ISSUE THREAD

**Issue by payamrastogi** [real-coddicted/react-tax-dashboard#80]

**Comment by jainanupam** [comment]
![Uploading Screenshot 2024-07-16 at 12.02.39 AM.png…]()
authorisedPerson field is coming in getAll response now, but not populating on the UI.

**Comment by payamrastogi** [comment]
![image](https://github.com/user-attachments/assets/e21a876c-8a6b-41c9-a6f0-b1081f467e5e)
